## Test 3.0


In [1]:
num = int(input("Enter a number: "))
if num % 2 == 0:
    print("the number is even!")
else:
    print("the number is odd!")

Enter a number:  333


the number is odd!


In [2]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [4]:
num = int(input("enter a number (0 to stop): "))
while num !=0:
    num = int(input("enter a number (0 to stop): "))

enter a number (0 to stop):  1
enter a number (0 to stop):  4
enter a number (0 to stop):  8
enter a number (0 to stop):  0


In [6]:
def add_numbers(a,b):
    return a+b

In [ ]:
What will be the output of this code: print(list(map(lambda x: x*x, [1, 2, 3])))?

In [ ]:
[1,4,9]

In [7]:
even_numbers = list(filter(lambda x: x % 2 == 0, [1, 2, 3, 4, 5, 6]))
print(even_numbers)

[2, 4, 6]


Explain the purpose of the else block in a try-except-else construct.

In [ ]:
"try block" it may raise an exception.
"except block" if an exception occurs in the try block, this block is executed.
"else block" this block runs only if the try block completes the successfully, which means no exception is raised.

In [8]:
try:
    numerator = 10
    denominator = 0
    result = numerator / denominator
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

Error: Cannot divide by zero.


In [ ]:
8

In [10]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
    def bark(self):
        print(f"{self.name} says: Woof!")

In [11]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
    def bark(self):
        print(f"{self.name} says: Woof!")
dog1 = Dog("Max", "Labrador")
dog2 = Dog("Bella", "Beagle")
dog1.bark()
dog2.bark()


Max says: Woof!
Bella says: Woof!


In [ ]:
instance variables are defined inside the __init__ method using self and these instance variables are unique to each object(instance) of the class.
class variables are defined direclty inside the class, outside any method and shared by all instances of the class.

In [ ]:
apple

In [13]:
def square_numbers(numbers):
    return [x ** 2 for x in numbers]


In [ ]:
1: The map() function applies a given function to all items in an input iterable and returns a new map object, which is an iterator that yields the results of applying the function.
2: The filter() function filters out elements from an iterable based on a condition defined by a function. it returns only the elements for which the funstion returns true.

### Numpy

In [14]:
import numpy as np
matrix = np.random.randint(0, 10, (3, 3))
print(matrix)

[[3 5 7]
 [6 2 6]
 [9 6 6]]


In [15]:
import numpy as np
matrix = np.random.randint(0, 10, (3, 3))
sliced_matrix = matrix[:2, :]
print(sliced_matrix)


[[0 7 7]
 [4 6 8]]


Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

In [16]:
import numpy as np
matrix1 = np.random.randint(0, 10, (3, 3))
matrix2 = np.random.randint(0, 10, (3, 3))
combined_axis_0 = np.concatenate((matrix1, matrix2), axis=0)
combined_axis_1 = np.concatenate((matrix1, matrix2), axis=1)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("\nCombined along axis 0 (vertically):\n", combined_axis_0)
print("\nCombined along axis 1 (horizontally):\n", combined_axis_1)


Matrix 1:
 [[8 9 6]
 [4 6 9]
 [3 4 6]]
Matrix 2:
 [[8 1 2]
 [5 9 5]
 [6 9 4]]

Combined along axis 0 (vertically):
 [[8 9 6]
 [4 6 9]
 [3 4 6]
 [8 1 2]
 [5 9 5]
 [6 9 4]]

Combined along axis 1 (horizontally):
 [[8 9 6 8 1 2]
 [4 6 9 5 9 5]
 [3 4 6 6 9 4]]


In [17]:
import numpy as np

matrix1 = np.random.randint(0, 10, (2, 2))
matrix2 = np.random.randint(0, 10, (2, 2))
dot_product = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Dot Product:\n", dot_product)


Matrix 1:
 [[4 8]
 [0 4]]
Matrix 2:
 [[8 8]
 [6 5]]
Dot Product:
 [[80 72]
 [24 20]]


In [19]:
import numpy as np

array_2D = np.random.randint(1, 10, (3, 3))
array_1D = np.array([1, 2, 3])
result = array_2D + array_1D
print("2D Array:\n", array_2D)
print("1D Array:\n", array_1D)
print("Result of Broadcasting:\n", result)


2D Array:
 [[8 3 5]
 [2 8 1]
 [4 3 5]]
1D Array:
 [1 2 3]
Result of Broadcasting:
 [[ 9  5  8]
 [ 3 10  4]
 [ 5  5  8]]


In [20]:
import numpy as np

matrix = np.array([[1, 5, 9],
                   [3, 8, 12],
                   [0, 7, 6]])
clipped_matrix = np.clip(matrix, 2, 8)

print("Original Matrix:")
print(matrix)
print("\nClipped Matrix (values between 2 and 8):")
print(clipped_matrix)


Original Matrix:
[[ 1  5  9]
 [ 3  8 12]
 [ 0  7  6]]

Clipped Matrix (values between 2 and 8):
[[2 5 8]
 [3 8 8]
 [2 7 6]]


In [21]:
import numpy as np

arr = np.array([1.2, 2.5, 3.8])
ceil_arr = np.ceil(arr)
print("Original Array:", arr)
print("Ceiling Array:", ceil_arr)

Original Array: [1.2 2.5 3.8]
Ceiling Array: [2. 3. 4.]


In [22]:
import numpy as np

arr = np.array([2, 6, 3, 8, 1, 5, 7])
modified_arr = np.where(arr > 5, 100, arr)

print("Original Array:", arr)
print("Modified Array:", modified_arr)


Original Array: [2 6 3 8 1 5 7]
Modified Array: [  2 100   3 100   1   5 100]


In [23]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
dot_product = np.dot(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nDot Product of A and B:")
print(dot_product)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Dot Product of A and B:
[[19 22]
 [43 50]]


In [ ]:
The difference between np.array([1, 2, 3]) and np.array([[1, 2, 3]]) is in the shape of the arrays they create. the np.array([1,2,3]) this create a 1-dimentional array where as np.array([1,2,3]) this creates a 2-dimensional array where there is 1 row and 3 columns.